[package]
name = "stt-clavier"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
psutil = "3.2.2"
gtk = "0.18.1"
glib = "0.10"
single-instance = "0.3"